
device: 'cuda:0'
name: 'thermal'  
# dataset ['esac1','esac2','valdo']
dataset:
  name: Multispectral 
  DESKTOP-SSEDT6V: 'E:\Dataset\greenAI\learning'
  DESKTOP-5V7R599: 'D:\OneDrive - isr.uc.pt\Datasets\greenAI\learning'
  train: ['esac1','esac2']
  test:  ['valdoeiro']
  loader:
    shuffle: False
    batch_size: 1
    workers: 1 
  augment: False  
# Model to be loaded
network: 
  model: 'segnet'
  input_shape: [240,240]
  drop_rate: 0.5
  bands:
    R: False
    G: False
    B: False
    RE: False
    NIR: False 
    thermal: True
  index:
    NDVI: False

  pretrained: 
    use: False
    path: 'checkpoints\t1\ms'
    file: 'thermal_segnet_best'
# training parameters
max_epochs: 100
report_val: 5
# optimization parameters
optimizer:
  lr: 0.001
  w_decay: 0
  amsgrad: True
  betas: [0.9, 0.99]
  epsilon_w:  0.000000001 
# Saving settings
saver:
  file: t1
  result_dir: 'results'  
  prediction_dir: 'prediction'

  
