
device: 'cuda:1'
name: 'hd_rbg'  
# dataset ['esac1','esac2','valdo']
dataset:
  name: x7 
  #root: '/home/tiago/remote_dataset/dataset/greenAI/learning/'
  root: /home/tiago/big/dataset/greenAI/learning/
  #DESKTOP-5V7R599: 'D:\OneDrive - isr.uc.pt\Datasets\greenAI\learning'
  train: ['qtabaixo']
  test:  ['qtabaixo']
  #train: ['esac1','esac2']
  #test:  [qtabaixo,'valdoeiro']
  loader:
    shuffle: False
    batch_size: 2
    workers: 0
  augment: False  
# Model to be loaded
network: 
  model: 'segnet'
  input_shape: [240,240]
  drop_rate: 0.5
  bands:
    R: True
    G: True
    B: True
    RE: False
    NIR: False 
    thermal: False
  index:
    NDVI: False
  pretrained: 
    use: False
    path: 'checkpoints\t1\hd'
    file: 'segnet_best'
# training parameters
max_epochs: 100
report_val: 5
# optimization parameters
optimizer:
  lr: 0.001
  w_decay: 0
  amsgrad: True
  betas: [0.9, 0.99]
  epsilon_w:  0.000000001 
# Saving settings
saver:
  file: t1
  result_dir: 'results'  
  prediction_dir: 'prediction'

  
