
device: 'cuda:0'
name: 'hd_rbg' 
run: 'NEW_RUN/hd'
# dataset ['esac1','esac2','valdo']
dataset:
  name: x7 
  #root: '/home/tiago/remote_dataset/dataset/greenAI/learning/'
  root: /home/tiago/big/dataset/greenAI/learning/
  #DESKTOP-5V7R599: 'D:\OneDrive - isr.uc.pt\Datasets\greenAI\learning'
  train: ['esac','valdoeiro']
  test:  ['qtabaixo']
  #train: ['esac1','esac2']
  #test:  [qtabaixo,'valdoeiro']
  fraction: 1
  loader:
    shuffle: True
    batch_size: 1
    workers: 0
  augment: True  
# Model to be loaded
network: 
  model: 'segnet'
  input_shape: [240,240]
  drop_rate: 0.5
  bands:
    R: True
    G: True
    B: True
    RE: False
    NIR: False 
    thermal: False
  index:
    NDVI: False
  pretrained: 
    use: False
    save: True
    path: 'checkpoints/hd'
    file: 'best'
# training parameters
max_epochs: 50
report_val: 1
# optimization parameters
optimizer:
  lr: 0.0001
  w_decay: 0.00001
  amsgrad: True
  betas: [0.9, 0.99]
  epsilon_w:  0 
# Saving settings
saver:
  file: t1
  result_dir: 'results/hd'  
  prediction_dir: 'prediction'

  
