
device: 'cuda:0'
name: 'dev'
  
run: 'dev'
dataset:
  root: samples
  name: altum   
  train: [qtabaixo]
  test:  ['qtabaixo']
  loader:
    shuffle: True
    batch_size: 1
    workers: 1 
  augment: True 
  fraction: 0.5

# Model to be loaded
network: 
  model: 'segnet'
  input_shape: [240,240]
  drop_rate: 0.5
  bands:
    R: False
    G: False
    B: False
    RE: False
    NIR: True 
    thermal: False
  index:
    NDVI: False
  pretrained: 
    use: True
    path: 'checkpoints\t1\hd'
    file: 'segnet_best'
# training parameters
max_epochs: 2
report_val: 1
# optimization parameters
optimizer:
  lr: 0.0001
  w_decay: 0.000061268
  amsgrad: False
  betas: [0.9, 0.99]
  epsilon_w:  0 
# Saving settings
saver:
  file: t1
  result_dir: 'results'  
  prediction_dir: 'prediction'

  
