
device: 'cuda:0'
name: 'dev'
  

dataset:
  root: samples
  name: x7   
  train: [esac]
  test:  ['valdoeiro']
  loader:
    shuffle: True
    batch_size: 10
    workers: 1 
  augment: True 
  fraction: 0.2

# Model to be loaded
network: 
  model: 'segnet'
  input_shape: [240,240]
  drop_rate: 0.5
  bands:
    R: True
    G: True
    B: True
    RE: False
    NIR: False 
    thermal: False
  index:
    NDVI: False
  pretrained: 
    use: False
    path: 'checkpoints\t1\hd'
    file: 'segnet_best'
# training parameters
max_epochs: 50
report_val: 1
# optimization parameters
optimizer:
  lr: 0.001
  w_decay: 0
  amsgrad: True
  betas: [0.9, 0.99]
  epsilon_w:  0.000000001 
# Saving settings
saver:
  file: t1
  result_dir: 'results'  
  prediction_dir: 'prediction'

  
