dataset:
  DESKTOP-5V7R599: D:\OneDrive - isr.uc.pt\Datasets\greenAI\learning
  DESKTOP-SSEDT6V: E:\Dataset\greenAI\learning
  augment: true
  fraction: 1
  loader:
    batch_size: 1
    shuffle: false
    workers: 1
  name: x7
  test:
  - qtabaixo
  train:
  - esac
  - valdoeiro
device: cuda:0
max_epochs: 1
name: nir
network:
  bands:
    B: false
    G: false
    NIR: true
    R: false
    RE: false
    thermal: false
  drop_rate: 0.5
  index:
    NDVI: false
  input_shape:
  - 240
  - 240
  model: segnet
  pretrained:
    file: re_nir_segnet_best
    path: ms/nir/t1
    use: false
optimizer:
  amsgrad: false
  betas:
  - 0.9
  - 0.99
  epsilon_w: 1.0e-09
  lr: 0.1
  w_decay: 6.1268e-05
report_val: 1
run: ms_test
saver:
  file: segnet_t1
  prediction_dir: prediction
  result_dir: results/ms_test
