dataset:
  DESKTOP-5V7R599: D:\OneDrive - isr.uc.pt\Datasets\greenAI\learning
  DESKTOP-SSEDT6V: E:\Dataset\greenAI\learning
  augment: true
  fraction: 0.01
  loader:
    batch_size: 1
    shuffle: false
    workers: 1
  name: altum
  test:
  - qtabaixo
  train:
  - esac
  - valdoeiro
device: cuda:0
max_epochs: 1
name: rgb
network:
  bands:
    B: true
    G: true
    NIR: false
    R: true
    RE: false
    thermal: false
  drop_rate: 0.5
  index:
    NDVI: false
  input_shape:
  - 240
  - 240
  model: segnet
  pretrained:
    file: rgb_segnet_best
    path: ms/rgb/t1
    save: true
    use: false
optimizer:
  amsgrad: false
  betas:
  - 0.9
  - 0.99
  epsilon_w: 1.0e-09
  lr: 0.0001
  w_decay: 4.0e-05
report_val: 1
run: paper_____/ms
saver:
  file: segnet_t1
  prediction_dir: prediction
  result_dir: results/paper_____/ms
